name: Deploy camping microservices on Kubernetes

on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install yamlpath==2.3.4
        yaml-set --change=host_ip --value="localhost" inputs.yml
        yaml-set --change=location --value=secrets.AZURE_LOCATION inputs.yml
        yaml-set --change=azure_credentials.username --value=secrets.AZURE_USERNAME inputs.yml
        yaml-set --change=azure_credentials.password --value=secrets.AZURE_PASSWORD inputs.yml
        yaml-set --change=resource_group_name --value=secrets.AZURE_RESOURCE_GROUP inputs.yml
          yaml-set --change=camping_overview_ms_db_connection_string --value=secrets.CAMPING_OVERVIEW_MS_DB_CONNENCTION_STRING inputs.yml
        yaml-set --change=camping_reservations_ms_db_connection_string --value=secrets.CAMPING_RESERVATIONS_MS_DB_CONNENCTION_STRING inputs.yml
        yaml-set --change=camping_opinions_ms_db_connection_string --value=secrets.CAMPING_OPINIONS_MS_DB_CONNENCTION_STRING inputs.yml
        yaml-set --change=camping_images_ms_postgres_credentials.username --value=secrets.CAMPING_IMAGES_MS_POSTGRES_USERNAME inputs.yml
        yaml-set --change=camping_images_ms_postgres_credentials.password --value=secrets.CAMPING_IMAGES_MS_POSTGRES_PASSWORD inputs.yml
    - name: Run deployment
      run: opera deploy -i inputs.yml service_template.yml
