name: Validate deloyment of camping microservices on Kubernetes

on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Install preprequisites
        run: |
          python -m pip install --upgrade pip
          pip install opera==0.6.3
          opera validate -i inputs.yml service_template.yml

      - name: Validate TOSCA service template
        run: opera validate -i inputs.yml service_template.yml
